# Generated by Django 5.2.13 on 2026-05-24 02:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("laundry_package", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode_nota",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "nama_customer",
                    models.CharField(help_text="Nama walk-in customer", max_length=100),
                ),
                (
                    "nomor_hp",
                    models.CharField(
                        help_text="Nomor HP customer (format Indonesia)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Nomor telepon harus format Indonesia murni angka (contoh: 08123456789 atau +628123456789).",
                                regex="^(?:\\+62|0)8[1-9][0-9]{8,11}$",
                            )
                        ],
                    ),
                ),
                (
                    "berat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "total_harga",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        choices=[
                            ("DITERIMA", "Diterima"),
                            ("DICUCI", "Dicuci"),
                            ("DIKERINGKAN", "Dikeringkan"),
                            ("DISETRIKA", "Disetrika"),
                            ("SELESAI", "Selesai"),
                            ("DIAMBIL", "Diambil"),
                        ],
                        default="DITERIMA",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("UNPAID", "Belum Bayar"), ("PAID", "Sudah Bayar")],
                        default="UNPAID",
                        max_length=10,
                    ),
                ),
                ("tanggal_order", models.DateTimeField(auto_now_add=True)),
                ("tanggal_update", models.DateTimeField(auto_now=True)),
                (
                    "nota_pdf",
                    models.FileField(blank=True, null=True, upload_to="nota/"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="laundry_package.laundrypackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-tanggal_order"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("teks", models.TextField()),
                ("reply", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["kode_nota"], name="orders_orde_kode_no_310868_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["progress_status", "payment_status"],
                name="orders_orde_progres_684e72_idx",
            ),
        ),
    ]
