# Generated by Django 5.2.13 on 2026-06-07 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DITERIMA", "Diterima"),
                            ("DICUCI", "Dicuci"),
                            ("DIKERINGKAN", "Dikeringkan"),
                            ("DISETRIKA", "Disetrika"),
                            ("SELESAI", "Selesai"),
                            ("DIAMBIL", "Diambil"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Perubahan Status",
                "verbose_name_plural": "Log Perubahan Status",
                "ordering": ["changed_at"],
            },
        ),
    ]
