# Generated by Django 5.2.13 on 2026-05-09 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaundryPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nama Paket"
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Harga per Kilogram (Rp)",
                    ),
                ),
                (
                    "estimated_days",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Estimasi Durasi (hari)"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Mulai Berlaku"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Berakhir Berlaku"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Deskripsi Detail Paket"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paket Laundry",
                "verbose_name_plural": "Paket Laundry",
                "ordering": ["price_per_kg"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="laundry_pac_is_acti_efb9da_idx",
                    )
                ],
            },
        ),
    ]
